services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: api
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
